import dotenv from 'dotenv';
import path from 'path';
import os from 'os';

// Load .env from project root
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

export interface PromptPlaceholders {
  default_prompt_boot: string;
  default_prompt_step1: string;
  default_prompt_step2a: string;
  default_prompt_step2b: string;
  default_prompt_step2c: string;
  default_prompt_step3: string;
  default_prompt_step4: string;
  default_prompt_step5a: string;
  default_prompt_step5b: string;
  default_prompt_step5c: string;
  default_prompt_step6: string;
  [key: string]: string;
}

export const config = {
  port: parseInt(process.env.PORT || '3001', 10),
  mongoUri: process.env.MONGO_URI || 'mongodb://localhost:27017/moltbot-orchestration',
  codaApiKey: process.env.CODA_API_KEY || '',
  codaDocId: process.env.CODA_DOC_ID || '',
  codaTableId: process.env.CODA_TABLE_ID || '',
  wsUrl: process.env.WS_URL || 'ws://127.0.0.1:18789/',
  panelCount: 6,
  validationMarkers: {
    step1: '=== END OF STEP 1 ===',
  },

  // Resilience settings for browser-dependent steps
  stepTransitionDelayMs: parseInt(process.env.STEP_TRANSITION_DELAY_MS || '5000', 10),      // delay between steps
  panelRetryCount: parseInt(process.env.PANEL_RETRY_COUNT || '2', 10),                      // max retries on transient failure
  panelRetryDelayMs: parseInt(process.env.PANEL_RETRY_DELAY_MS || '10000', 10),             // delay between retries
  browserStepTimeoutMs: parseInt(process.env.BROWSER_STEP_TIMEOUT_MS || '600000', 10),      // timeout for browser-dependent steps (default 10 minutes)

  // OS-level Browser Control
  // Use OpenClaw's dedicated Chrome user-data-dir so we skip the profile picker
  // and launch directly into the profile that has the relay extension installed.
  chromeExePath: process.env.CHROME_EXE_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  openclawUserDataDir: process.env.OPENCLAW_CHROME_USER_DATA_DIR || path.join(os.homedir(), '.openclaw', 'browser', 'openclaw', 'user-data'),
  browserOpenCmd: process.env.BROWSER_OPEN_CMD || 'cmd /c start "" "{{CHROME_EXE}}" --remote-debugging-port=18800 --user-data-dir="{{USER_DATA_DIR}}" "chrome-extension://{{EXTENSION_ID}}/chatHub.html"',
  browserCloseCmd: process.env.BROWSER_CLOSE_CMD || 'powershell -Command "Get-WmiObject Win32_Process -Filter \\"Name=\'chrome.exe\'\\" | Where-Object { $_.CommandLine -like \'*openclaw*\' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }"',
  extensionId: process.env.SIMPLE_CHAT_HUB_EXT_ID || 'your-extension-id-here',
  cdpPort: parseInt(process.env.CDP_PORT || '18800', 10),
  panelWaitTimeMs: parseInt(process.env.PANEL_WAIT_TIME_MS || '120000', 10),  // 2 minutes default
} as const;

// Prompt placeholders — opinionated defaults, editable from frontend
// These are simple, direct MoltBot commands — not elaborate structured instructions.
export const promptPlaceholders: PromptPlaceholders = {
  default_prompt_boot: `end with 
=== END OF STEP 0 ===`,

  // Step 1 is now handled entirely by CDP (wait + read panel responses).
  // No MoltBot prompt needed — the output is generated by the server.
  default_prompt_step1: `CDP_HANDLED`,


default_prompt_step2a: `Below are the full AI panel responses extracted from Simple Chat Hub. Analyze them thoroughly.

{{PANEL_RESPONSES}}

Using ONLY the information above, produce exactly these five sections:
1. Common Themes
2. Major Differences
3. Strengths and Weaknesses
4. Missing Areas
5. Preliminary Conclusion

You MUST still produce these five sections even if some or all panels had "No visible response" (in that case, explain that as part of Missing Areas / Preliminary Conclusion).

End your response with exactly this marker on its own line:
=== END OF STEP 2A ===`,

  default_prompt_step2b: `Based on the analysis below, perform a cross-review and produce a final consolidated analysis.

INPUT:
{{STEP2A_OUTPUTS}}

You must:
- Compare the findings
- Resolve contradictions
- Strengthen weak areas
- Produce a refined synthesis

OUTPUT:
1. Comparative Summary
2. Resolved Conflicts
3. Final Consolidated Analysis

End your response with:
=== END OF STEP 2B ===`,

  default_prompt_step2c: `Based on the consolidated analysis below, perform a final quality evaluation.

INPUT:
{{STEP2B_OUTPUTS}}

Score the analysis on 8 criteria (1-5 each) to ensure it meets high research standards.

OUTPUT:
1. Score Table
2. Total Quality Score
3. Evaluation Summary

End your response with:
=== END OF STEP 2C ===`,

  default_prompt_step3: `Produce the first-round consolidated research document.

Analysis Input:
{{ANALYSIS_INPUT}}

Quality Evaluation:
{{QUALITY_EVALUATION}}

OUTPUT:
1. Final Executive Summary
2. Detailed Findings
3. Integrated Insights
4. Final Recommendations
5. Gap List (bullet points of missing information, uncited claims, or areas needing deeper research)

End your response with:
=== END OF STEP 3 ===`,

  // ─── Round 2: Gap Research ───

  // Step 4 is now handled entirely by CDP (type gap query + wait + read panel responses).
  // No MoltBot prompt needed — the output is generated by the server.
  default_prompt_step4: `CDP_HANDLED`,


  default_prompt_step5a: `Below are the full AI panel responses extracted from Simple Chat Hub for the gap research round. Analyze them thoroughly.

{{PANEL_RESPONSES}}

Using ONLY the information above, produce exactly these five sections:
1. Common Themes
2. Major Differences
3. Strengths and Weaknesses
4. Missing Areas
5. Preliminary Conclusion

End your response with:
=== END OF STEP 5A ===`,

  default_prompt_step5b: `Based on the gap analysis below, perform a cross-review and produce a final consolidated gap analysis.

Original Research (Round 1):
{{ROUND1_OUTPUT}}

New Gap Research:
{{STEP5A_OUTPUTS}}

You must:
- Compare the new gap findings with the original research
- Resolve contradictions
- Fill in the gaps that were identified
- Produce a refined synthesis that strengthens the original research

OUTPUT:
1. Comparative Summary
2. Resolved Gaps
3. Final Consolidated Gap Analysis

End your response with:
=== END OF STEP 5B ===`,

  default_prompt_step5c: `Based on the consolidated gap analysis below, perform a final quality evaluation.

INPUT:
{{STEP5B_OUTPUTS}}

Score the analysis on 8 criteria (1-5 each) to ensure it meets high research standards.

OUTPUT:
1. Score Table
2. Total Quality Score
3. Evaluation Summary

End your response with:
=== END OF STEP 5C ===`,

  default_prompt_step6: `Produce the final, complete research document by merging the original research with the gap research.

Original Research (Round 1):
{{ROUND1_OUTPUT}}

Gap Analysis:
{{GAP_ANALYSIS_INPUT}}

Gap Quality Evaluation:
{{GAP_QUALITY_EVALUATION}}

OUTPUT:
1. Final Executive Summary
2. Comprehensive Findings (original + gap research merged)
3. Integrated Insights
4. Final Recommendations
5. Remaining Limitations (if any)

End your response with:
=== END OF STEP 6 ===`,
};

export function updatePromptPlaceholder(key: string, value: string): void {
  promptPlaceholders[key] = value;
}
